version: '3'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    tty: true
    volumes:
      - ../:/workspace
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - 9001:5432
    volumes:
      - type: bind
        source: "../data"
        target: "/var/lib/postgresql/data"
